Initial check-in of branch dm900

diff --git a/flash-fsbl b/flash-fsbl
--- a/flash-fsbl
+++ b/flash-fsbl
@@ -1,55 +1,58 @@
 #!/bin/sh
 #
-# Copyright (C) 2020 Dream Property GmbH
+# Copyright (C) 2016 Dream Property GmbH
 #
 
 source librecovery
 
-flash_uboot()
-{
-	local pkgdatadir="/usr/share/u-boot-bin/dream${MACHINE}"
-	if ! is_directory "${pkgdatadir}"; then
-		pkgdatadir="/usr/share/u-boot-bin"
-	fi
-	local uboot_bin="${pkgdatadir}/u-boot.bin"
-	local uboot_env="${pkgdatadir}/u-boot.env"
+read MID </proc/stb/info/mid
+OTP=$(readspi --otp -c 192 | base64 | tr -d '\n' | tr '+' '-' | tr '/' '_')
+SHA=$(readspi -c $((3*512*1024)) | sha256sum | awk '{print $1}')
 
-	is_readable_file "${uboot_bin}" || abort "Cannot access '${uboot_bin}'"
-	is_readable_file "${uboot_env}" || abort "Cannot access '${uboot_env}'"
+[ -n "${MID}" ] || abort 'Failed to read model ID'
+[ -n "${OTP}" ] || abort 'Failed to read OTP data'
+[ -n "${SHA}" ] || abort 'Failed to hash FSBL'
 
-	create_workspace
-	create_keyring "${RECOVERY_KEY}"
-	verify "${uboot_bin}"
-
-	is_file_size_le "${uboot_bin}" "${UBOOT_SIZE}" || abort "U-Boot image is too big"
-	is_writable_blockdev "${UBOOT_PARTITION}" || abort "Target device '${UBOOT_PARTITION}' is not writable"
-
-	source "${uboot_env}"
-
-	local new_hash=$(sha256sum "${uboot_bin}" | awk '{print $1}')
-	for size in ${UBOOT_KNOWN_SIZES}; do
-		local old_hash=$(dd "if=${UBOOT_PARTITION}" "bs=$((${size} + 512))" count=1 2>/dev/null | dd skip=1 2>/dev/null | sha256sum | awk '{print $1}')
-		if [ "${old_hash}" = "${new_hash}" ]; then
-			info "Skipping update of same version of U-Boot"
-			return
-		fi
-
-		local uboot_known_hashes="UBOOT_KNOWN_HASHES_${size}"
-		for known_hash in ${!uboot_known_hashes}; do
-			if [ "${old_hash}" = "${known_hash}" ]; then
-				info "Updating U-Boot"
-				write_lba "${uboot_bin}" "${UBOOT_PARTITION}" 1
-				return
-			fi
-		done
-	done
-
-	abort "Refusing to overwrite an unknown bootloader version"
-}
+URI="http://dreambox.de/verify/fsbl?m=${MID}&o=${OTP}&s=${SHA}"
 
 xgetopts $@
-if [ -n "${UBOOT_PARTITION}" ]; then
-	flash_uboot
-else
-	info "Nothing to do"
-fi
+create_workspace
+
+export GNUPGHOME="${WORKSPACE}"
+
+(base64 -d > trustedkeys.gpg || abort 'Failed to write public key') << EOF
+mQENBFhPLT4BCACu7IxjzWdrzWYh0lbFx9AvMmniszx67gAvvz0AMlug25TsVo+2u+YMacK5QX6b
+8GLkuUYCETZzadaSoOd3WqUadjmtgqa1+G4BZPEHSuyrmMGuathRWCHXJ0dXC7d41ckZS0ufpHM7
+/a9MBh4sJUdrVrGCvxfRYms/R3CrWJgEcZGgHfeS85XFTAQygALnLtk4j/12am9npLDOFAfxy5D1
+GOi832omdu+QeCLpBqjCXbYm3C6+Vwpkm/780o0tGAuogKhflsc0C9ax50oEtj/G7xLCoIjcKpxr
+mX3fh6kxD54mIj0nMSvSJiDkLICDBsKRuOJ+HCrqo0yK5r6LsH2TABEBAAG0NURyZWFtYm94IERN
+OTAwIChGU0JMIHVwZGF0ZSkgPGRtOTAwQGZzYmwuZHJlYW1ib3guZGU+iQE4BBMBAgAiBQJYTy0+
+AhsDBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRBo07UpmBtXLJrCB/4u4tsMBivjsKlrGdvu
+/QiOO2+CO2XXItfFctyOgUsqIUonYAJK6BUv2rb0wMqSjwGcqjQjqdtefe4aILqZKqjlyneIkyrx
+J7e/W24g43xo6tVGQuX8RXXEGeN2NaqVL3HUi+BAvPwAqZujQn0RA8VLE8U5KrdAhKm5VxcnHurh
+AaqnV6GBTmjIqJSLMzIcUAqi4Y1Pv2FfHMYJZetArH0CQFH2BZthhheWj/BvKOSBJUFMcWGpwZeo
+sPMw9rDJPziwiMhLqFlLip3bk4PU1NSSluTvPyxoVh43P4flCSuvZKZgz/aJ+6IB8O1SYLPRu+51
+kII48WItRJMlH2Fpur47uQENBFhPLT4BCACyzVlv6Ne3JodR+yihnizl622H8xstIqXVVXnmUwBR
+rbQg4/NpqtDNEIh1GdhLgE3F+dFMRBlNFsGcHbEhmB9Gn0LNHFjDkKB4/LFqVh2k4aemRF6xafkd
+kZNwMU390OG21AgxGYoOP/YDqHKEdQ0+H+1qjyIuCu66UwX1U22Y6si9iXhBVXEkv+Ga4b1LMCoX
+M/664oeU2hey7UcWkiFibJ8E2jLGIu4+8wNBDvt9I+2p6gSlu6xwvUSmpBhU+wo2/+uav7WAb6Ub
+bpRZ6URvb2F0o2xSJ7FlRYyGGCcOXcLYRQzUt2ataS7th1/NNKmtSUFwCemrQJU9Lpt+NtHPABEB
+AAGJAR8EGAECAAkFAlhPLT4CGwwACgkQaNO1KZgbVyy4pgf/TVckA31sAHQXwkzvF5rmRo/KqBBL
+pRtCaY+48l/Ac5aXT1evsjRZKBCkU4QOkJsytP0E3Rj/o8kAcT34uS+7J4xZGdyM+hcR6huA4CDK
+z6gz3op9mGHF0PIbY7cm6tu+k32iuy+Tp5a3oPywUSkoMw8FT6GwmSf3VADOMR3TdiTP9XRvhgGW
+qCtHm0s91wOwsYifEDyNLg39QW801YXKup7Gj7E0u8p1c9Ey+Gifio/YrAB4YaJuP0uaM2Mt6OJp
+kl9JWN12d5M7linrcbpm2/WpzKzSfw5LEtzZSeEO0CaYRwhoYKxUsaMZwMFGtuUDw34RbHDqfpok
+s3F9cSJ97g==
+EOF
+
+info "Downloading '${URI}'"
+wget -q "${URI}" -O fsbl-flasher.tgz >&3 2>&4
+
+create_directory fsbl-flasher
+extract_tarball fsbl-flasher.tgz fsbl-flasher
+verify fsbl-flasher/fsbl-flasher
+
+info "Running fsbl-flasher"
+chmod 755 fsbl-flasher/fsbl-flasher || abort "Failed to set execute permissions"
+xtrap fsbl-flasher/fsbl-flasher || abort "Failed to execute fsbl-flasher"
+info "Done."
diff --git a/recovery b/recovery
--- a/recovery
+++ b/recovery
@@ -1,9 +1,11 @@
+#!/bin/sh
 #
 # Copyright (C) 2016 Dream Property GmbH
 #
 
+BASE_URI=http://dreamboxupdate.com/download/recovery/dm900/release
+FILENAME=dreambox-image-dm900.tar.xz
 MMC_DEVICE=/dev/mmcblk0
-KERNEL_PARTITION=/dev/mmcblk0p1
 ROOT_PARTITION=/dev/mmcblk0p2
 ROOT_MOUNTPOINT=/mnt
 ROOT_NAME=dreambox-rootfs
@@ -21,21 +23,6 @@ set -e
 exec 3>/dev/null
 exec 4>&2
 exec 5>&1
-
-is_beneath_directory()
-{
-	local file=`xrealpath ${1}`
-	local dir=`xrealpath ${2}`
-
-	case "$file" in
-		$dir/*)
-			true
-			;;
-		*)
-			false
-			;;
-	esac
-}
 
 is_blockdev()
 {
@@ -62,11 +49,6 @@ is_readable()
 	[ -r "${1}" ]
 }
 
-is_readable_blockdev()
-{
-	is_blockdev "${1}" && is_readable "${1}"
-}
-
 is_readable_file()
 {
 	is_file "${1}" && is_readable "${1}"
@@ -87,19 +69,9 @@ is_writable_chardev()
 	is_chardev "${1}" && is_writable "${1}"
 }
 
-is_writable_directory()
-{
-	is_directory "${1}" && is_writable "${1}"
-}
-
 is_empty()
 {
 	[ -z "${1}" ]
-}
-
-is_file_size_le()
-{
-	[ "`stat -c '%s' ${1}`" -le "${2}" ]
 }
 
 is_initrd()
@@ -184,12 +156,6 @@ erase()
 	xtrap flash_erase "${1}" 0 0
 }
 
-write_nand()
-{
-	info "Writing to NAND memory on ${1}"
-	xtrap nandwrite -p -m "${1}" "${2}"
-}
-
 format_ubi_device()
 {
 	info "Formatting ${1} for UBI"
@@ -223,66 +189,6 @@ create_partition_table()
 		-n 3:2097152: -c 3:data -t 3:8300 "${1}"
 }
 
-create_tarball()
-{
-	local sysroot="${1}"
-	local tarball="${2}"
-	local opt
-
-	case "${tarball}" in
-		*.tar)
-			opt=""
-			;;
-		*.gz|*.tgz|*.taz)
-			opt="-z"
-			;;
-		*.Z|*.taZ)
-			opt="-Z"
-			;;
-		*.bz2|*.tbz|*.tbz2|*.tz2)
-			opt="-j"
-			;;
-		*.lz)
-			opt="--lzip"
-			;;
-		*.lzma|*.tlz)
-			opt="--lzma"
-			;;
-		*.lzo)
-			opt="--lzop"
-			;;
-		*.xz|*.txz)
-			opt="-J"
-			;;
-		*)
-			abort "Invalid file type: ${tarball}"
-			;;
-	esac
-
-	create_directory "`dirname ${tarball}`"
-
-	echo "${WORKSPACE:1}" >exclude.list
-	(cd "${sysroot}" && find . -type s) >>exclude.list
-
-	if [ $# -gt 2 ]; then
-		printf "" >include.list
-		IFS=$'\n'
-		set -- ${3}
-		unset IFS
-		for path; do
-			if [ -e "${sysroot}${path}" ]; then
-				echo "${path:1}" >>include.list
-			fi
-		done
-	else
-		echo "." >include.list
-	fi
-
-	info "Creating ${tarball} from ${sysroot}"
-	xtar -C "${sysroot}" ${opt} --exclude-from=exclude.list --files-from=include.list -cf "${tarball}.tmp"
-	mv "${tarball}.tmp" "${tarball}"
-}
-
 create_workspace()
 {
 	umask 077
@@ -294,12 +200,8 @@ create_workspace()
 
 extract_tarball()
 {
-	local tarball="${1}"
-	local dir="${2}"
-	shift 2
-
-	info "Extracting '${tarball}' to '${dir}'"
-	xtar -xf "${tarball}" -C "${dir}" $@
+	info "Extracting '${1}' to '${2}'"
+	xtar -xf "${1}" -C "${2}"
 }
 
 fetch()
@@ -408,17 +310,6 @@ unmount_cache()
 	unmount "${DATA_MOUNTPOINT}"
 }
 
-run()
-{
-	local cmd="${1}"
-	shift
-
-	info "Running '${cmd}'"
-	is_empty "$@" || info "Options '$@'"
-	chmod 755 "${cmd}" || abort "Failed to set execute permissions"
-	${cmd} $@ || abort "Failed to execute '${cmd}'"
-}
-
 run_postinsts()
 {
 	local virtfs="dev proc run sys tmp"
@@ -452,27 +343,9 @@ assert_rescue_mode()
 	is_initrd || is_nfsroot || abort "This script may only run in rescue mode!"
 }
 
-write_blkdev()
-{
-	info "Writing ${1} to ${2}"
-	xdd if=${1} of=${2} bs=64K
-}
-
-write_lba()
-{
-	info "Writing ${1} to ${2} (LBA: ${3})"
-	xdd if="${1}" of="${2}" bs=512 seek="${3}"
-}
-
-select_boot_source()
-{
-	info "Enabling boot source ${2}"
-	printf "opt${2}\0" | xdd of=${1} bs=512 seek=64
-}
-
 usage()
 {
-	echo "Usage: ${0} [-hqtv]"
+	echo "Usage: ${0} [-bhqrtv]"
 	exit ${1}
 }
 
@@ -517,15 +390,6 @@ xdd()
 	xtrap dd conv=fsync $@
 }
 
-xgetopts()
-{
-	local opt
-
-	while getopts hqtv opt; do
-		std_opt "${opt}"
-	done
-}
-
 xrealpath()
 {
 	local opt
@@ -556,3 +420,77 @@ xtrap()
 {
 	(trap '' HUP INT TERM; exec $@) >&3 2>&4
 }
+
+BACKUP_SETTINGS=":"
+RESTORE_SETTINGS=":"
+SETTINGS="settings.tar.gz"
+
+while getopts bhqrtv opt; do
+	case "${opt}" in
+		b)
+			BACKUP_SETTINGS="backup-settings ${SETTINGS}"
+			;;
+		r)
+			RESTORE_SETTINGS="restore-settings ${SETTINGS}"
+			;;
+	esac
+	std_opt "${opt}"
+done
+
+assert_rescue_mode
+
+is_writable_blockdev "${MMC_DEVICE}" || abort "Target block device '${MMC_DEVICE}' is not a writable block device"
+
+create_workspace
+export GNUPGHOME="${WORKSPACE}"
+
+(base64 -d > trustedkeys.gpg || abort 'Failed to write public key') << EOF
+mQENBFfS0TQBCADLP/mDLWiIF/dJmVFVzQf9CJ7jtb5ilVf4SOasXkPEbdtDsvIIE8ShAHPUgmYC
+YGAl5FJNxaPZMhyylC9BZOLeYdUgJVRJXjY2WX/bE/6/J5z9UWj+XPzbnbxC+ZnzOGwyUAiHtwbF
+YLH0SnCN6LEl+nqgwRwpKBgFp64YyAAJ/Rpj5tK6T9v5QuN5CK/UcClmLSqlC/KSbjf93+W9AyOM
+9F/apxNnhWyEPPjEQbJV8G1WTDL12j4NER3CwwGr+WlKidNdtqDZYYMx89p/qLoV0kbk8tOB7Szx
+STFQIpetPi++WlKduS5K1gmVYSU8v9WdSAIDujbH1lqOtBq6AaIFABEBAAG0NERyZWFtYm94IERN
+OTAwIFJlY292ZXJ5IDxkbTkwMEByZWNvdmVyeS5kcmVhbWJveC5kZT6JATgEEwECACIFAlfS0TQC
+GwMGCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJEPAqD3Z9onVhi9YIALa4eA9XRbyNT/kz2fj9
+gJ9aLfoxPACbkc2pxwVmLtqeCvsgzEvG62QkFwfL+HDQy2G3YgOSYM8/Z1Y8Agp0iS/QNzNE9v7u
+cniOy7bX+L+M/zZtLnmY4ixIWcPdMraipjaH3v1c9SUg4eeN6WRgQnPmDA2w+PBViXoAAuqKQrG/
+7DrGLzXiUzRgxoub4hm1au6KSnEgthn7O33dtCKRDwlCFDHNqdOpgayfGKZ+ENrP5FPZIuSmJH+Z
+GWxsi2P4cmVwsSE0i1REX3pk1xd4lefdmminxhgsrHnlh4q5O6fSrSlIfNKZ3SZZ3KeSCB21g/9L
+5jAezlvBvp2M0qC2EDQ=
+EOF
+
+mount_cache
+fetch_signed "${BASE_URI}" "${FILENAME}"
+
+[ ! -f "${RECOVERY_CACHE}/settings.tar.gz" ] || cp ${RECOVERY_CACHE}/settings.tar.gz ${SETTINGS}
+if blkdev_has_filesystem "${ROOT_PARTITION}"; then
+	${BACKUP_SETTINGS}
+fi
+[ "${RESTORE_SETTINGS}" = ":" -o -f "${SETTINGS}" ] || abort "Can't restore settings without prior backup!"
+
+if ! is_blockdev "${ROOT_PARTITION}" || ! blkdev_has_filesystem "${DATA_PARTITION}"; then
+	unmount "${ROOT_MOUNTPOINT}" || abort "Failed to unmount root filesystem"
+	unmount "${DATA_MOUNTPOINT}" || abort "Failed to unmount data filesystem"
+	if ! is_blockdev "${ROOT_PARTITION}" || ! is_blockdev "${DATA_PARTITION}"; then
+		create_partition_table "${MMC_DEVICE}" || abort "Failed to partition disk"
+	fi
+	if ! blkdev_has_filesystem "${DATA_PARTITION}"; then
+		create_filesystem "${DATA_NAME}" "${DATA_PARTITION}" || warn "Failed to create ${FILESYSTEM} filesystem '${DATA_NAME}' on '${DATA_PARTITION}'"
+	fi
+	mount_cache
+fi
+
+unmount "${ROOT_MOUNTPOINT}" || abort "Failed to unmount root filesystem"
+create_filesystem "${ROOT_NAME}" "${ROOT_PARTITION}" || abort "Failed to create ${FILESYSTEM} filesystem '${ROOT_NAME}' on '${ROOT_PARTITION}'"
+safe_mount "${ROOT_PARTITION}" "${ROOT_MOUNTPOINT}" || abort "Failed to mount root filesystem"
+extract_tarball "${FILENAME}" "${ROOT_MOUNTPOINT}" || abort "Failed to extract root filesystem"
+run_postinsts "${ROOT_MOUNTPOINT}" kernel-image || abort "Failed to run postinst scripts"
+${RESTORE_SETTINGS}
+unmount "${ROOT_MOUNTPOINT}" || warn "Failed to unmount root filesystem"
+
+[ "${BACKUP_SETTINGS}" = ":" ] || update_cache "${SETTINGS}"
+update_cache_signed "${FILENAME}"
+unmount_cache
+
+info "Initiating reboot"
+sync && reboot || warn 'Failed to initiate reboot'
