Initial check-in of branch dm7080

diff --git a/flash-kernel b/flash-kernel
--- a/flash-kernel
+++ b/flash-kernel
@@ -1,18 +1,17 @@
 #!/bin/sh
 #
-# Copyright (C) 2019 Dream Property GmbH
+# Copyright (C) 2014 Dream Property GmbH
 #
 
 source librecovery
 
-case "${MACHINE}" in
-	one|two|seven)
-		DEVICETREE=/boot/dream${MACHINE}.dtb
-		CMDLINE=
-		INITRD=
-		OPTSTRING="c:d:hi:qtv"
-		;;
-esac
+MEM_SIZE=0x10000000
+ARC_IMAGES=/usr/share/fastboot/lcd_anim.bin
+MAX_IMAGE_SIZE=$((32 * 1024 * 1024))
+OPTION=A
+VMLINUX=
+CMDLINE=
+INITRD=
 
 create_blob()
 {
@@ -39,31 +38,6 @@ create_blob()
 	mkbootblob ${ARGS} >&3 2>&4
 }
 
-create_bootimg()
-{
-	ARGS="--base 0 --kernel_offset 0x1080000 --second_offset 0x1000000 -o ${1}"
-
-	ARGS="${ARGS} --kernel ${VMLINUX}"
-	if is_readable_file "${DEVICETREE}"; then
-		ARGS="${ARGS} --second ${DEVICETREE}"
-	fi
-	if is_readable_file "${INITRD}"; then
-		ARGS="${ARGS} --ramdisk ${INITRD}"
-	fi
-	ARGS="${ARGS} --board ${MACHINE}"
-
-	info "Creating boot image - cmdline=${CMDLINE}"
-	if is_empty "${CMDLINE}"; then
-		mkbootimg ${ARGS} >&3 2>&4
-	else
-		if is_gpt; then
-			CMDLINE=$(echo ${CMDLINE} | sed -e "s/mmcblk0p7/${CMDLINE_ROOTFS}/g")
-		fi
-		info "Kernel command-line: ${CMDLINE}"
-		mkbootimg ${ARGS} --cmdline "${CMDLINE}" >&3 2>&4
-	fi
-}
-
 write_blob()
 {
 	case "${3}" in
@@ -78,21 +52,18 @@ write_blob()
 
 usage()
 {
-	echo "Usage: ${0} [-hqtv] [-c <cmdline>] [-d <devicetree>] [-i <initrd>] <vmlinux.bin>"
-	echo "       Default: -d ${DEVICETREE}"
+	echo "Usage: ${0} [-hqtv] [-a <arc images>] [-c <cmdline>] [-i <initrd>] [-m <mem-size>] [-o A|B] <vmlinux.bin>"
+	echo "       Default: -a ${ARC_IMAGES} -m ${MEM_SIZE} -o ${OPTION}"
 	exit ${1}
 }
 
-while getopts ${OPTSTRING} opt; do
+while getopts a:c:hi:m:o:qtv opt; do
 	case "${opt}" in
 		a)
 			ARC_IMAGES="${OPTARG}"
 			;;
 		c)
 			CMDLINE="${OPTARG}"
-			;;
-		d)
-			DEVICETREE="${OPTARG}"
 			;;
 		i)
 			INITRD="${OPTARG}"
@@ -111,22 +82,26 @@ shift $((${OPTIND} - 1))
 [ "$#" -eq 1 ] || usage 1
 VMLINUX=`xrealpath ${1}`
 
+is_writable_blockdev "${MMC_DEVICE}" || abort "Target block device '${MMC_DEVICE}' is not a writable block device"
+IFS=:
+for FILE in ${ARC_IMAGES}; do
+	is_readable_file "${FILE}" || abort "Cannot access '${FILE}'"
+done
+unset IFS
+is_empty "${INITRD}" || is_readable_file "${INITRD}" || abort "Cannot access '${INITRD}'"
 ! is_empty "${VMLINUX}" || abort "No kernel image given"
 is_readable_file "${VMLINUX}" || abort "Cannot access '${VMLINUX}'"
-is_file_size_le "${VMLINUX}" "${KERNEL_SIZE}" || abort "Kernel image is too big"
 
-DEVICE=${KERNEL_PARTITION:-${FLASH_DEVICE}}
-is_writable_blockdev "${DEVICE}" || is_writable_chardev "${DEVICE}" || abort "Target device '${DEVICE}' is not writable"
-
-case "${MACHINE}" in
-	one|two|seven)
-		create_workspace
-		if is_gpt; then
-			create_bootimg "/boot/kernel.img" || abort "Failed to create boot image"
-		else
-			create_bootimg bootblob.bin || abort "Failed to create boot image"
-			is_file_size_le bootblob.bin "${KERNEL_SIZE}" || abort "Boot image is too big"
-			write_blkdev bootblob.bin "${KERNEL_PARTITION}" || abort "Failed to flash boot image"
-		fi
+case "${OPTION}" in
+	A|B)
+		;;
+	*)
+		abort "Invalid boot option: ${OPTION}"
 		;;
 esac
+
+create_workspace
+create_blob bootblob.bin || abort "Failed to create boot image"
+is_file_size_le bootblob.bin "${MAX_IMAGE_SIZE}" || abort "Boot image is too big"
+write_blob bootblob.bin "${MMC_DEVICE}" "${OPTION}" || abort "Failed to flash boot image"
+select_boot_source "${MMC_DEVICE}" "${OPTION}" || abort "Failed to enable boot source"
diff --git a/recovery b/recovery
--- a/recovery
+++ b/recovery
@@ -1,7 +1,10 @@
+#!/bin/sh
 #
 # Copyright (C) 2016 Dream Property GmbH
 #
 
+BASE_URI=http://dreamboxupdate.com/download/recovery/dm7080/release
+FILENAME=dreambox-image-dm7080.tar.xz
 MMC_DEVICE=/dev/mmcblk0
 ROOT_PARTITION=/dev/mmcblk0p1
 ROOT_MOUNTPOINT=/mnt
@@ -20,21 +23,6 @@ set -e
 exec 3>/dev/null
 exec 4>&2
 exec 5>&1
-
-is_beneath_directory()
-{
-	local file=`xrealpath ${1}`
-	local dir=`xrealpath ${2}`
-
-	case "$file" in
-		$dir/*)
-			true
-			;;
-		*)
-			false
-			;;
-	esac
-}
 
 is_blockdev()
 {
@@ -61,11 +49,6 @@ is_readable()
 	[ -r "${1}" ]
 }
 
-is_readable_blockdev()
-{
-	is_blockdev "${1}" && is_readable "${1}"
-}
-
 is_readable_file()
 {
 	is_file "${1}" && is_readable "${1}"
@@ -86,19 +69,9 @@ is_writable_chardev()
 	is_chardev "${1}" && is_writable "${1}"
 }
 
-is_writable_directory()
-{
-	is_directory "${1}" && is_writable "${1}"
-}
-
 is_empty()
 {
 	[ -z "${1}" ]
-}
-
-is_file_size_le()
-{
-	[ "`stat -c '%s' ${1}`" -le "${2}" ]
 }
 
 is_initrd()
@@ -168,7 +141,14 @@ create_filesystem()
 
 blkdev_has_filesystem()
 {
-	is_blockdev "${1}" && blkid -o export "${1}" | grep -q "^TYPE=${FILESYSTEM}$"
+	is_blockdev "${1}" && (
+		if hash blkid 2>/dev/null; then
+			blkid -o export "${1}" | grep -q "^TYPE=${FILESYSTEM}$"
+		else
+			local dir=`mktemp -d -p ${WORKSPACE}` || abort 'Failed to create temporary mount point'
+			grep -q "^${1}\s[^\s]\+\s${FILESYSTEM}\s" /proc/mounts || (mount -t ${FILESYSTEM} -o ro "${1}" "${dir}" 2>/dev/null && umount "${dir}")
+		fi
+	)
 }
 
 create_nand_filesystem()
@@ -181,12 +161,6 @@ erase()
 {
 	info "Erasing flash memory on ${1}"
 	xtrap flash_erase "${1}" 0 0
-}
-
-write_nand()
-{
-	info "Writing to NAND memory on ${1}"
-	xtrap nandwrite -p -m "${1}" "${2}"
 }
 
 format_ubi_device()
@@ -216,69 +190,16 @@ create_ubi_volume()
 create_partition_table()
 {
 	info "Creating partition table"
-	xtrap sgdisk -z \
-		-n 1:147456:2097151 -c 1:rootfs -t 1:8307 \
-		-n 2:2097152: -c 2:data -t 2:8300 "${1}"
-}
-
-create_tarball()
-{
-	local sysroot="${1}"
-	local tarball="${2}"
-	local opt
-
-	case "${tarball}" in
-		*.tar)
-			opt=""
-			;;
-		*.gz|*.tgz|*.taz)
-			opt="-z"
-			;;
-		*.Z|*.taZ)
-			opt="-Z"
-			;;
-		*.bz2|*.tbz|*.tbz2|*.tz2)
-			opt="-j"
-			;;
-		*.lz)
-			opt="--lzip"
-			;;
-		*.lzma|*.tlz)
-			opt="--lzma"
-			;;
-		*.lzo)
-			opt="--lzop"
-			;;
-		*.xz|*.txz)
-			opt="-J"
-			;;
-		*)
-			abort "Invalid file type: ${tarball}"
-			;;
-	esac
-
-	create_directory "`dirname ${tarball}`"
-
-	echo "${WORKSPACE:1}" >exclude.list
-	(cd "${sysroot}" && find . -type s) >>exclude.list
-
-	if [ $# -gt 2 ]; then
-		printf "" >include.list
-		IFS=$'\n'
-		set -- ${3}
-		unset IFS
-		for path; do
-			if [ -e "${sysroot}${path}" ]; then
-				echo "${path:1}" >>include.list
-			fi
-		done
+	if hash sgdisk 2>/dev/null; then
+		xtrap sgdisk -z \
+			-n 1:147456:2097151 -c 1:rootfs -t 1:8307 \
+			-n 2:2097152: -c 2:data -t 2:8300 "${1}"
 	else
-		echo "." >include.list
+		xtrap parted --script --align=optimal "${1}" -- \
+			mklabel gpt \
+			mkpart primary ext2 72MiB 1GiB \
+			mkpart primary ext2 1GiB 100% >&3 2>&4
 	fi
-
-	info "Creating ${tarball} from ${sysroot}"
-	xtar -C "${sysroot}" ${opt} --exclude-from=exclude.list --files-from=include.list -cf "${tarball}.tmp"
-	mv "${tarball}.tmp" "${tarball}"
 }
 
 create_workspace()
@@ -292,12 +213,8 @@ create_workspace()
 
 extract_tarball()
 {
-	local tarball="${1}"
-	local dir="${2}"
-	shift 2
-
-	info "Extracting '${tarball}' to '${dir}'"
-	xtar -xf "${tarball}" -C "${dir}" $@
+	info "Extracting '${1}' to '${2}'"
+	xtar -xf "${1}" -C "${2}"
 }
 
 fetch()
@@ -406,17 +323,6 @@ unmount_cache()
 	unmount "${DATA_MOUNTPOINT}"
 }
 
-run()
-{
-	local cmd="${1}"
-	shift
-
-	info "Running '${cmd}'"
-	is_empty "$@" || info "Options '$@'"
-	chmod 755 "${cmd}" || abort "Failed to set execute permissions"
-	${cmd} $@ || abort "Failed to execute '${cmd}'"
-}
-
 run_postinsts()
 {
 	local virtfs="dev proc run sys tmp"
@@ -450,27 +356,9 @@ assert_rescue_mode()
 	is_initrd || is_nfsroot || abort "This script may only run in rescue mode!"
 }
 
-write_blkdev()
-{
-	info "Writing ${1} to ${2}"
-	xdd if=${1} of=${2} bs=64K
-}
-
-write_lba()
-{
-	info "Writing ${1} to ${2} (LBA: ${3})"
-	xdd if="${1}" of="${2}" bs=512 seek="${3}"
-}
-
-select_boot_source()
-{
-	info "Enabling boot source ${2}"
-	printf "opt${2}\0" | xdd of=${1} bs=512 seek=64
-}
-
 usage()
 {
-	echo "Usage: ${0} [-hqtv]"
+	echo "Usage: ${0} [-bhqrtv]"
 	exit ${1}
 }
 
@@ -515,15 +403,6 @@ xdd()
 	xtrap dd conv=fsync $@
 }
 
-xgetopts()
-{
-	local opt
-
-	while getopts hqtv opt; do
-		std_opt "${opt}"
-	done
-}
-
 xrealpath()
 {
 	local opt
@@ -554,3 +433,77 @@ xtrap()
 {
 	(trap '' HUP INT TERM; exec $@) >&3 2>&4
 }
+
+BACKUP_SETTINGS=":"
+RESTORE_SETTINGS=":"
+SETTINGS="settings.tar.gz"
+
+while getopts bhqrtv opt; do
+	case "${opt}" in
+		b)
+			BACKUP_SETTINGS="backup-settings ${SETTINGS}"
+			;;
+		r)
+			RESTORE_SETTINGS="restore-settings ${SETTINGS}"
+			;;
+	esac
+	std_opt "${opt}"
+done
+
+assert_rescue_mode
+
+is_writable_blockdev "${MMC_DEVICE}" || abort "Target block device '${MMC_DEVICE}' is not a writable block device"
+
+create_workspace
+export GNUPGHOME="${WORKSPACE}"
+
+(base64 -d > trustedkeys.gpg || abort 'Failed to write public key') << EOF
+mQENBFPo2oUBCAC6dzqe5azBCkxzj99xNfzwB4L6tHzz83zqD2KUQuuJMhO7Q2g9AHnSNQ0z1+Bz
+oX2gGX90FusBSLiCuZmNdnxlcl7KVfBe37EpYtQNGCZKlWeruCAUdJGKIyPJXDvkXCy3dj6z1ho8
+p1r3uazEbUbJyLvwjzcg0Ua1qxFjLoq/h15yDgd0NCkMStL6gwKdmReLRfE/tn0K53CVQzIeEFyn
+EW3N0tu2deiYkanHy/MM9IOIv3oQmoEWNaVsDf+gG7nUPj0QE66GOYlBugR5vNi3BorOctarQp/8
+Dh56muiqomwwewJubzsvjUjpiYXdO/3RN2gOej2+5hUCiYmvOahfABEBAAG0LkRyZWFtYm94IERN
+NzA4MCBSZWNvdmVyeSA8cmVjb3ZlcnlAZG03MDgwLmNvbT6JATgEEwECACIFAlPo2oUCGwMGCwkI
+BwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJEBWob67Wz1bnUGYH/0zmTS7Gtvv97oHHnz3JSkLybDRj
+Jx/wH+vpzyCRl8rC7TlHs5GBfjoJ1Hjo4DsZqElTb8g+kg5WGzMBUUuwabRhZuf2CL7/IPKP+LWH
+t2ByZX3OgS1Q+HDLob5wlKllD9y/wwekuwS/8cgdnDH9URHCBqIt5gWQzLU1pvmQrKPXM1aMsLQj
+16vbktXNkREF/cNhWfQFQs2dOwmzNEDeuE32I6h7PYl1bFP0hCOmbkcTuibnC+tsWOJMKF1iZ8bq
+xDND9BYTwGtD2SVrddu3i4kBz6hka01ZnfSUZewpu+TrCgaD6oENfarPiC9VYfKEFi10RIPIxwRX
+s1tBOOQNKpywAgAD
+EOF
+
+mount_cache
+fetch_signed "${BASE_URI}" "${FILENAME}"
+
+[ ! -f "${RECOVERY_CACHE}/settings.tar.gz" ] || cp ${RECOVERY_CACHE}/settings.tar.gz ${SETTINGS}
+if blkdev_has_filesystem "${ROOT_PARTITION}"; then
+	${BACKUP_SETTINGS}
+fi
+[ "${RESTORE_SETTINGS}" = ":" -o -f "${SETTINGS}" ] || abort "Can't restore settings without prior backup!"
+
+if ! is_blockdev "${ROOT_PARTITION}" || ! blkdev_has_filesystem "${DATA_PARTITION}"; then
+	unmount "${ROOT_MOUNTPOINT}" || abort "Failed to unmount root filesystem"
+	unmount "${DATA_MOUNTPOINT}" || abort "Failed to unmount data filesystem"
+	if ! is_blockdev "${ROOT_PARTITION}" || ! is_blockdev "${DATA_PARTITION}"; then
+		create_partition_table "${MMC_DEVICE}" || abort "Failed to partition disk"
+	fi
+	if ! blkdev_has_filesystem "${DATA_PARTITION}"; then
+		create_filesystem "${DATA_NAME}" "${DATA_PARTITION}" || warn "Failed to create ${FILESYSTEM} filesystem '${DATA_NAME}' on '${DATA_PARTITION}'"
+	fi
+	mount_cache
+fi
+
+unmount "${ROOT_MOUNTPOINT}" || abort "Failed to unmount root filesystem"
+create_filesystem "${ROOT_NAME}" "${ROOT_PARTITION}" || abort "Failed to create ${FILESYSTEM} filesystem '${ROOT_NAME}' on '${ROOT_PARTITION}'"
+safe_mount "${ROOT_PARTITION}" "${ROOT_MOUNTPOINT}" || abort "Failed to mount root filesystem"
+extract_tarball "${FILENAME}" "${ROOT_MOUNTPOINT}" || abort "Failed to extract root filesystem"
+run_postinsts "${ROOT_MOUNTPOINT}" dreambox-secondstage kernel-image || abort "Failed to run postinst scripts"
+${RESTORE_SETTINGS}
+unmount "${ROOT_MOUNTPOINT}" || warn "Failed to unmount root filesystem"
+
+[ "${BACKUP_SETTINGS}" = ":" ] || update_cache "${SETTINGS}"
+update_cache_signed "${FILENAME}"
+unmount_cache
+
+info "Initiating reboot"
+sync && reboot || warn 'Failed to initiate reboot'
diff --git a/run-recovery b/run-recovery
--- a/run-recovery
+++ b/run-recovery
@@ -1,11 +1,11 @@
 #!/bin/sh
 #
-# Copyright (C) 2016 Dream Property GmbH
+# Copyright (C) 2014 Dream Property GmbH
 #
 
 source librecovery
 
-BASE_URI=http://dreamboxupdate.com/download/recovery/${MACHINE}/release
+BASE_URI=http://dreamboxupdate.com/download/recovery/dm7080/release
 FILENAME=recovery
 
 while getopts bhqrtv opt; do
@@ -13,7 +13,23 @@ while getopts bhqrtv opt; do
 done
 assert_rescue_mode
 create_workspace
-create_keyring "${RECOVERY_KEY}"
+
+export GNUPGHOME="${WORKSPACE}"
+
+(base64 -d > trustedkeys.gpg || abort 'Failed to write public key') << EOF
+mQENBFPo2oUBCAC6dzqe5azBCkxzj99xNfzwB4L6tHzz83zqD2KUQuuJMhO7Q2g9AHnSNQ0z1+Bz
+oX2gGX90FusBSLiCuZmNdnxlcl7KVfBe37EpYtQNGCZKlWeruCAUdJGKIyPJXDvkXCy3dj6z1ho8
+p1r3uazEbUbJyLvwjzcg0Ua1qxFjLoq/h15yDgd0NCkMStL6gwKdmReLRfE/tn0K53CVQzIeEFyn
+EW3N0tu2deiYkanHy/MM9IOIv3oQmoEWNaVsDf+gG7nUPj0QE66GOYlBugR5vNi3BorOctarQp/8
+Dh56muiqomwwewJubzsvjUjpiYXdO/3RN2gOej2+5hUCiYmvOahfABEBAAG0LkRyZWFtYm94IERN
+NzA4MCBSZWNvdmVyeSA8cmVjb3ZlcnlAZG03MDgwLmNvbT6JATgEEwECACIFAlPo2oUCGwMGCwkI
+BwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJEBWob67Wz1bnUGYH/0zmTS7Gtvv97oHHnz3JSkLybDRj
+Jx/wH+vpzyCRl8rC7TlHs5GBfjoJ1Hjo4DsZqElTb8g+kg5WGzMBUUuwabRhZuf2CL7/IPKP+LWH
+t2ByZX3OgS1Q+HDLob5wlKllD9y/wwekuwS/8cgdnDH9URHCBqIt5gWQzLU1pvmQrKPXM1aMsLQj
+16vbktXNkREF/cNhWfQFQs2dOwmzNEDeuE32I6h7PYl1bFP0hCOmbkcTuibnC+tsWOJMKF1iZ8bq
+xDND9BYTwGtD2SVrddu3i4kBz6hka01ZnfSUZewpu+TrCgaD6oENfarPiC9VYfKEFi10RIPIxwRX
+s1tBOOQNKpywAgAD
+EOF
 
 mount_cache
 fetch_signed "${BASE_URI}" "${FILENAME}"
